server:
  port: 9002

eureka:
  client:
    service-url:
      defaultZone: http://eureka:123456@${spring.cloud.client.ip-address}:9000/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    status-page-url-path: /#/applications
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}

spring:
  application:
    name: admin
  security:
    user:
      name: admin
      password: 123456

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

info:
  name: ${spring.application.name}
  version : 0.5

